# Generated by cpp11: do not edit by hand

collectorGuess <- function(input, locale_, guessInteger) {
  .Call(`_minty_collectorGuess`, input, locale_, guessInteger)
}

utctime_ <- function(year, month, day, hour, min, sec, psec) {
  .Call(`_minty_utctime_`, year, month, day, hour, min, sec, psec)
}

parse_vector_ <- function(x, collectorSpec, locale_, na, trim_ws) {
  .Call(`_minty_parse_vector_`, x, collectorSpec, locale_, na, trim_ws)
}

type_convert_col <- function(x, spec, locale_, col, na, trim_ws) {
  .Call(`_minty_type_convert_col`, x, spec, locale_, col, na, trim_ws)
}
