# Generated by cpp11: do not edit by hand

collectorGuess <- function(input, locale_, guessInteger, guess_max) {
  .Call(`_minty_collectorGuess`, input, locale_, guessInteger, guess_max)
}

parse_vector_ <- function(x, collectorSpec, locale_, na, trim_ws) {
  .Call(`_minty_parse_vector_`, x, collectorSpec, locale_, na, trim_ws)
}

type_convert_col <- function(x, spec, locale_, col, na, trim_ws) {
  .Call(`_minty_type_convert_col`, x, spec, locale_, col, na, trim_ws)
}

r_is_string_cpp11 <- function(x) {
  .Call(`_minty_r_is_string_cpp11`, x)
}
